/* 
 * TrackServer
 *
 * Server for People Tracking System
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace IO.Swagger.Model
{
    /// <summary>
    /// InlineResponse200
    /// </summary>
    [DataContract]
    public partial class InlineResponse200 :  IEquatable<InlineResponse200>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponse200" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected InlineResponse200() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponse200" /> class.
        /// </summary>
        /// <param name="Latitude">Latitude (required).</param>
        /// <param name="Longtitude">Longtitude (required).</param>
        /// <param name="IsCaptain">IsCaptain (required).</param>
        public InlineResponse200(string Latitude = null, string Longtitude = null, bool? IsCaptain = null)
        {
            // to ensure "Latitude" is required (not null)
            if (Latitude == null)
            {
                throw new InvalidDataException("Latitude is a required property for InlineResponse200 and cannot be null");
            }
            else
            {
                this.Latitude = Latitude;
            }
            // to ensure "Longtitude" is required (not null)
            if (Longtitude == null)
            {
                throw new InvalidDataException("Longtitude is a required property for InlineResponse200 and cannot be null");
            }
            else
            {
                this.Longtitude = Longtitude;
            }
            // to ensure "IsCaptain" is required (not null)
            if (IsCaptain == null)
            {
                throw new InvalidDataException("IsCaptain is a required property for InlineResponse200 and cannot be null");
            }
            else
            {
                this.IsCaptain = IsCaptain;
            }
        }
        
        /// <summary>
        /// Gets or Sets Latitude
        /// </summary>
        [DataMember(Name="latitude", EmitDefaultValue=false)]
        public string Latitude { get; set; }
        /// <summary>
        /// Gets or Sets Longtitude
        /// </summary>
        [DataMember(Name="longtitude", EmitDefaultValue=false)]
        public string Longtitude { get; set; }
        /// <summary>
        /// Gets or Sets IsCaptain
        /// </summary>
        [DataMember(Name="isCaptain", EmitDefaultValue=false)]
        public bool? IsCaptain { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineResponse200 {\n");
            sb.Append("  Latitude: ").Append(Latitude).Append("\n");
            sb.Append("  Longtitude: ").Append(Longtitude).Append("\n");
            sb.Append("  IsCaptain: ").Append(IsCaptain).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as InlineResponse200);
        }

        /// <summary>
        /// Returns true if InlineResponse200 instances are equal
        /// </summary>
        /// <param name="other">Instance of InlineResponse200 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponse200 other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Latitude == other.Latitude ||
                    this.Latitude != null &&
                    this.Latitude.Equals(other.Latitude)
                ) && 
                (
                    this.Longtitude == other.Longtitude ||
                    this.Longtitude != null &&
                    this.Longtitude.Equals(other.Longtitude)
                ) && 
                (
                    this.IsCaptain == other.IsCaptain ||
                    this.IsCaptain != null &&
                    this.IsCaptain.Equals(other.IsCaptain)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Latitude != null)
                    hash = hash * 59 + this.Latitude.GetHashCode();
                if (this.Longtitude != null)
                    hash = hash * 59 + this.Longtitude.GetHashCode();
                if (this.IsCaptain != null)
                    hash = hash * 59 + this.IsCaptain.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
